### ISSUE TITLE
github badge

### ISSUE THREAD

**Issue by lukeschafer** [OctopusDeploy/ICanHasDotnetCore#1]
it would be super cool to have a buildstatus-style badge to indicate compliance.

`.net core|compliant`
`.net core|non-compliant`

or similar

**Comment by droyad** [comment]
You mean to put on their github page/website? Or in the app. 

Perhaps
`.NET Standard|1.4`
`.NET Standard|unsupported`

**Comment by lukeschafer** [comment]
On the page.  Like appveyor `build passing` badges.

**Comment by droyad** [comment]
We're not using a public build server anymore (TeamCity), but each of the commits has a status
