### ISSUE TITLE
Font extremely illegible

### ISSUE THREAD

**Issue by JesperTreetop** [OctopusDeploy/ICanHasDotnetCore#10]
The font is specified as `font-weight: 100;` and `font-family: Roboto, 'Helvetica Neue', sans-serif;`. This font weight is very spindly (regular font weight is 400 and bold is 700) and on a system like mine where a font is available for this font weight, [the body text is extremely illegible](http://imgur.com/DyIsurQ).

**Comment by droyad** [comment]
Thank you @JesperTreetop

**Comment by JesperTreetop** [comment]
That's much better! Thanks. 👍
