### ISSUE TITLE
Shouldn't packages with a portable PCL considered supported on .NET Standard?

### ISSUE THREAD

**Issue by dsyme** [OctopusDeploy/ICanHasDotnetCore#15]
Many packages (e.g. FSharp.Data) have a portable PCL (e.g. profile 7 or 259), which, if I'm not mistaken, can be used as .NET Standard components (if I'm not mistaken)?  However it appears these packages are being shown as "unsupported" with "no package available", e.g. in the package visualization for https://github.com/Microsoft/visualfsharp/blob/master/packages.config

(Note: It could be that your tool is being very smart and somehow knows that the particular dependency in question is on a net45 component in a package that also has a profile 259 component?  However the profile259 component is probably adequate to resolve the dependency)

**Comment by droyad** [comment]
Thank you for pointing this out @dsyme. Our tool is not being smart.

Do do this, we will need to look into the actual nuget packages to determine the platforms, so it is related to #9.

Ref: https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#portable-profiles.
