### ISSUE TITLE
Detect external imports / PInvokes

### ISSUE THREAD

**Issue by CraigStuntz** [OctopusDeploy/ICanHasDotnetCore#16]
My project [uses Win32 DLL imports](https://github.com/CraigStuntz/Fizil/blob/master/Fizil/WinApi.fs), but ICanHas doesn't seem to detect this. Would be nice if they were at least flagged.

**Comment by droyad** [comment]
@CraigStuntz Thanks for the suggestion. There is an existing tool that does a better job than we would. Check out this blog post: http://www.michael-whelan.net/porting-dotnet-framework-library-to-dotnet-core/). It is linked on our website, but maybe it's too hidden :).
