### ISSUE TITLE
Support for packages.ProjectName.json files

### ISSUE THREAD

**Issue by ryangribble** [OctopusDeploy/ICanHasDotnetCore#20]
Thanks for an awesome tool :+1:

Just as an FYI, over at [octokit.net](https://github.com/octokit/octokit.net) we have some packages.config files using the `packages.ProjectName.json` file name format (which AFAIK is a valid/supported thing in terms of nuget/visual studio) which don't appear to be picked up by an [ICanHasDotnetCore scan of the repo](https://icanhasdot.net/result?github=octokit~2Foctokit.net), unless I'm missing something

eg:
[packages.Octokit.Tests.config](https://github.com/octokit/octokit.net/blob/master/Octokit.Tests/packages.Octokit.Tests.config)
[packages.Octokit.Tests-NetCore45.config](https://github.com/octokit/octokit.net/blob/master/Octokit.Tests/packages.Octokit.Tests-NetCore45.config)
[packages.Octokit.Tests-Portable.config](https://github.com/octokit/octokit.net/blob/master/Octokit.Tests/packages.Octokit.Tests-Portable.config)

**Comment by alfhenrik** [comment]
As `packages.json` has been deprecated in favor of the new `.csproj` format we'll close this issue. Issue #24 will add support for the new `.csproj` format.
