### ISSUE TITLE
Allow to somehow save the results or results page

### ISSUE THREAD

**Issue by miguelcrpinto** [OctopusDeploy/ICanHasDotnetCore#22]
I just analysed all the packages on my solution and would be nice to be able to somehow save the results and suggestions. At the moment you only provide the graph data which is not that much worth it as I don't know which packages are compatible with .Net standard and which not.

**Comment by droyad** [comment]
Hi @miguelcrpinto, If you scroll down the page, you will see much more detail.

**Comment by miguelcrpinto** [comment]
@droyad I've seen those details and they help a lot but as soon as you refresh the page or close the tab the results are gone and then you have to upload all the package.config files again. Would be handy to have some results save feature so that you can see the results later.

As I mentioned before the graph data is nice to have but the most useful information (packages compatibility) cannot be saved... and this is what I'd like to save!

**Comment by miguelcrpinto** [comment]
You don't have to save them on a DB or anywhere else. Just allow them to be exported either as text in an email, PDF or something else
