### ISSUE TITLE
Dead link on stats page

### ISSUE THREAD

**Issue by 304NotModified** [OctopusDeploy/ICanHasDotnetCore#23]
The stats page (https://icanhasdot.net/Stats) has a deadlink (404):

![image](https://cloud.githubusercontent.com/assets/5808377/20098819/ecfe86f4-a5b5-11e6-9809-10bef9e13b5b.png)

----

![image](https://cloud.githubusercontent.com/assets/5808377/20098833/fc351138-a5b5-11e6-978a-9db509ffd90c.png)

**Comment by droyad** [comment]
Thanks. It is fixed.
