### ISSUE TITLE
Add support for Cypher output

### ISSUE THREAD

**Issue by cskardon** [OctopusDeploy/ICanHasDotnetCore#27]
I'd like to add another output type, `Cypher` - based on http://opencypher.org

It allows me to run queries against the data, for example, I can import into my DB and then query something like:

```
MATCH (p:InvestigationTarget)-[:REFERENCES]->(dependency)
RETURN count(dependency)
```

To get the number of dependencies for a given package.
Importing is straight forward - basically just a `CREATE` statement, and in keeping with the current `GraphViz` style approach would just be a `StringBuilder`

I'm not sure if you're accepting pull requests for this sort of change or not?

**Comment by droyad** [comment]
@cskardon Sounds good, go for it.

**Comment by cskardon** [comment]
OK, the Cypher output is easily done (and in fact *is* done), with the console app working as expected, but I have a couple of issues that might be blockers:

1. I only have VS2017 on my dev box, and opening the `.sln` caused an upgrade to the `xproj`s - so now they are all `csproj`.
2. I can't get the Web project to work - I can compile and run, but navigating to the correct location informs me I'm missing `~\index.html` - I'm not sure if this is something to do with the project update - I imagine it is as `dotnet new webapi` has a different structure - and adding a `wwwroot` folder and copying the `index.html` file to it, makes it work.

I'm wary about doing a full upgrade to the web app, as I'm not 100% au fait with core projects, and don't want to mess it up.

So - I guess - either knock this on the head for now, or I can attach the `CypherOutputFormatter.cs` here and someone else with a lower version of dotnet could do it...???

Any thoughts?

**Comment by droyad** [comment]
I've converted the project, so it should be good to open in VS2017 if you have dotnet-1.1.1-sdk (1.1.1 with SDK 1.0.1) installed (https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1.1-download.md).

Note that you can install multiple SDKs side by side, it's all controlled through the `global.json`.

You will need to run `build.cmd` to get the UI to build and install (see README.md). Or `npm install`, `gulp watch`.

**Comment by cskardon** [comment]
Thanks for updating the project, it made life a lot easier to have someone who understands it do it :)
