### ISSUE TITLE
version number is v0.0.0.0

### ISSUE THREAD

**Issue by iqans** [OctopusDeploy/ICanHasDotnetCore#31]
![image](https://user-images.githubusercontent.com/10431508/29077691-8f60eac4-7c50-11e7-8e3b-5b214659f30f.png)

footer of homepage.

**Comment by alfhenrik** [comment]
Thanks @iqans for letting us know, we'll have this fixed as soon as we can.

**Comment by alfhenrik** [comment]
Actually, after having a chat to the team, this has been fixed, but we haven't shipped the latest fixes to the production site. I'll do that this morning.

**Comment by alfhenrik** [comment]
This has now been pushed to the live site
