### ISSUE TITLE
Export to spreadsheet functionality

### ISSUE THREAD

**Issue by axd7832** [OctopusDeploy/ICanHasDotnetCore#36]
I believe that it would be super useful to have the data exported into a `.csv` or a similar format. 
For my use case- I am documenting each of the dependencies that are not .Net Core supported and I had to build a table with all of the same information that you provided to me.

**Comment by matt-richardson** [comment]
Hi @axd7832 - thanks for the suggestion.
We are unlikely to implement this ourselves, but we'd happily accept a PR for it!

**Comment by droyad** [comment]
@axd7832 You can use the [console](https://icanhasdot.net/Console) app to a get a flat list (`flat.txt`) of all the dependencies and their statuses

**Comment by axd7832** [comment]
Thanks for the fast response @matt-richardson . Unlikely that I'll put in a PR but thank you for the Console app suggestion @droyad
