### ISSUE TITLE
Fix link on error page

### ISSUE THREAD

**Issue by Nothing4You** [OctopusDeploy/ICanHasDotnetCore#38]
it currently links to https://github.com/OctopusDeploy/ICanHasDotnetCore/Issues which doesn't work. it needs to be https://github.com/OctopusDeploy/ICanHasDotnetCore/issues

**Comment by matt-richardson** [comment]
Thanks @Nothing4You, this is fixed. We'll push it out shortly.

**Comment by matt-richardson** [comment]
This was pushed out in 1.0.7. Thanks again!
